// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3cTjRAuY8cm0RilCFNnAqHm097NvxLSo',
    appId: '1:301754029580:web:YOUR_WEB_APP_ID',
    messagingSenderId: '301754029580',
    projectId: 'earth-vibe-f4c0b',
    authDomain: 'earth-vibe-f4c0b.firebaseapp.com',
    storageBucket: 'earth-vibe-f4c0b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3cTjRAuY8cm0RilCFNnAqHm097NvxLSo',
    appId: '1:301754029580:android:f866b38a4462bd7e428029',
    messagingSenderId: '301754029580',
    projectId: 'earth-vibe-f4c0b',
    storageBucket: 'earth-vibe-f4c0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3cTjRAuY8cm0RilCFNnAqHm097NvxLSo',
    appId: '1:301754029580:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '301754029580',
    projectId: 'earth-vibe-f4c0b',
    storageBucket: 'earth-vibe-f4c0b.firebasestorage.app',
    iosBundleId: 'com.upla.earthvibe',
  );
}
